### ISSUE TITLE
Feature request: Token TTL

### ISSUE THREAD

**Issue by manniL** [nuxt-community/auth-module#101]
Hey!

Setting a token TTL would be awesome!

Not sure if this is already possible in `dev` version, but it's not in `4.0.0-rc3`. 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c74">#c74</a>)</em></sub></div>

**Comment by robsontenorio** [comment]
it solves a problem about "auto refershing  tokens"?

**Comment by manniL** [comment]
Well, that depends on which kind of auth you use. It'd help with JWT at least, because you can update the token before it expires.

**Comment by robsontenorio** [comment]
I have a concret case with KEYCLOAK. After login it responds with access_token and refresh_token (both with expiration property in seconds). 

In my scenario the access_token last long five minutes. So, i need to write a axios plugin to intercept every single ajax request in order to check expiration and refresh token, before send a request to backend. Otherwise an exception would be trown. 

A built in solution would be nice to handle refresh tokens. 

--
Robson Tenório 

Em 15 de mar de 2018, à(s) 14:52, Alexander Lichter <notifications@github.com> escreveu:

**Comment by robsontenorio** [comment]
Please, check PR #103 

Keycloak
- It adds keycloak provider for oauth2

Global improvements
- Set authorization token for all axios requests (oauth2 scheme)
- Store refresh_token if exists

**Comment by robsontenorio** [comment]
This PR solve the problem for Oauth2 Scheme.
https://github.com/nuxt-community/auth-module/pull/188

As mentioned on #172 a similar policy should be implemented for LOCAL Scheme.

**Comment by JoaoPedroAS51** [comment]
Closing here, as auth v5 already has this feature.
