### ISSUE TITLE
Laravel Passport issue 

### ISSUE THREAD

**Issue by afaridanquah** [nuxt-community/auth-module#1022]
I get the below error for this version;

 "@nuxtjs/auth-next": "^5.0.0-1611346714.218633a",

ERROR  Cannot read property 'status' of undefined                                                     21:10:06

  at node_modules/@nuxtjs/auth-next/dist/module.js:153:43
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)

See below my strategy:
    strategies: {
      'platformApi': {
        provider: 'laravelPassport',
        grantType: 'password',
        endpoints: {
          user: {
            url: '/api/api/user',
          },
        },
        url: '/api',
        clientId: process.env.PASSPORT_CLIENT_ID,
        clientSecret: process.env.PASSPORT_CLIENT_SECRET,
      },
    },

Can you please take a look?

**Comment by bmulholland** [comment]
Sorry, but this isn't much information to go on. We don't have your setup or config, and so it's impossible for us to look into the issue. What we need is either a repro, or for you to drop a debugger statement in JS and trace through execution to the root cause of the problem.

At a bear minimum, please use our Issue template. Feel free to open a new issue using that.
