### ISSUE TITLE
After successful login loggedIn state is only set after page refresh (v5)

### ISSUE THREAD

**Issue by Alwigi** [nuxt-community/auth-module#1066]
### Version
module: 5.0.0-1613647907.37b1156
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [X ] universal
 - [ ] spa

### Nuxt configuration
  router: {
    middleware: ['auth']
  },

  auth: {
    strategies: {
      local: {
        token: {
          property: 'token',
          // required: true,
          // type: 'Bearer'
        },
        user: {
          property: 'user',
          autoFetch: false
        },
        endpoints: {
          login: { url: '/auth', method: 'post' },
          logout: { url: '/logout', method: 'post' },
          user: false, 
        }
      }
    }
  }

## Reproduction
Regular login to api using local/jwt is successful, token is returned and stored in local storage. No navigation works (always redirects to login page) until the page is refreshed, then navigation works as expected.
For simplicity I'm currently not using auth's redirect settings, just using navbar button navigation to manually navigate after login.

#### What is expected? 
Navigation to any secure page works after successful login

#### What is actually happening? 
Continually redirected to login page instead of navigating to secure page

#### Steps to reproduce: 
see details below

## Additional information
I intend using SSR but I have tried with SSR on and off and I see the same result. 
Update: Reverting to v4.9.1 works just fine (with SSR=true)

## Checklist
* [X]  I have tested with the latest Nuxt version and the issue still occurs
* [X]  I have tested with the latest module version and the issue still occurs
* [X]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
1. Navigate to app url for first time (user not logged in)
2. Home page is secured so auth redirects to login page as expected
3. Type credentials and login (console log shows that login is successful)
4. Use nav button to go to home page (or any other non-public page) but login page is shown again (loggedIn is set to false)
5. Hit F5
6. Use nav button to go to home page (or any other non-public page), only now does it work as expected  (loggedIn is set to true)

### What is expected?
Navigation to the desired secure page without page refresh

### What is actually happening?
App redirects back to the login page although user is logged in ie. blocks any navigation 
Refresh page F5, now navigation is working and loggedIn state is set to true

**Comment by Kaperskyguru** [comment]
I am currently having this issue too, same result as above.

**Comment by Alwigi** [comment]
I have done some more research and I am 99% sure there is a bug when setting the vuex loggedIn state.
I have set SSR=false and removed all async handling just to be safe, my login is called from a button click method and looks like this:

`    userLogin() {
      try {
        this.$auth.loginWith('local', { data: this.login })
          .then(() => {
            console.log('LOGGED IN'); //I see this
          })
      } catch (err) {
        console.log(err)
      }
    }`

After login the local storage and cookies are all set correctly but the store update does not complete here are the vuex logs:

`
    {"sideBarVisible":false,"auth":{"user":null,"loggedIn":false,"strategy":"local"}}    (mutate user to false)
    {"sideBarVisible":false,"auth":{"user":false,"loggedIn":false,"strategy":"local"}}   (mutate loggedIn to false)
    {"sideBarVisible":false,"auth":{"user":false,"loggedIn":false,"strategy":"local","busy":true}}    (mutate busy to true)
    {"sideBarVisible":false,"auth":{"user":false,"loggedIn":false,"strategy":"local","busy":false}}   (mutate busy to false)
    I'd expect to see loggedIn set to true here?
`
After F5 page refresh then auth is sorted, only then do I see the vuex update:

`
    {"sideBarVisible":false,"auth":{"user":{},"loggedIn":true,"strategy":"local","redirect":"__vue_devtool_undefined__"}}    (mutate loggedIn to true)
`

**Comment by Alwigi** [comment]
OK, by fluke I finally figured this out! 
The problem is the auth.strategies.local.user.autofetch setting, if set to true than all works fine but when set to false then the behaviour is as above.

I don't know if this is by design but it feels like a bug.

**Comment by JoaoPedroAS51** [comment]
> The problem is the auth.strategies.local.user.autofetch setting, if set to true than all works fine but when set to false then the behaviour is as above.

Hi @Alwigi! Yes, it's working as expected, this is not a bug. In order to `loggedIn` state be `true`, the user data must be set. When `autoFetch` is set to `false`, you must set the user manually with `setUser({...})` right after login.

[You can read this for more information](https://auth.nuxtjs.org/schemes/local#backend)

**Comment by DmitriyColors** [comment]
Hi guys

Have you been able to solve the problem?
I ran into the same situation., but the problem is not the redirection but the empty user state.
![2021-02-25 19_07_14-](https://user-images.githubusercontent.com/46503055/109167427-92b87680-779f-11eb-8386-3b03a198636d.png)

As soon as I add user data manually, a redirect occurs.
```
try {
        let response = await this.$auth.loginWith('local', { data: this.login })
        console.log(response)
        this.$auth.setUser(response.data.user)
        console.log('Yes')
      }
```
![2021-02-25 19_39_27-Window](https://user-images.githubusercontent.com/46503055/109169082-453d0900-77a1-11eb-9a9e-87c8ffdd2cd0.png)
![2021-02-25 19_41_42-Window](https://user-images.githubusercontent.com/46503055/109169468-a95fcd00-77a1-11eb-8ce0-82e35665c83f.png)


Everything would be fine, but after refreshing the page, the user data is reset
![2021-02-25 19_40_29-Window](https://user-images.githubusercontent.com/46503055/109169209-64d43180-77a1-11eb-840f-6bda7e09d6f7.png)
![2021-02-25 19_42_14-Window](https://user-images.githubusercontent.com/46503055/109169493-ad8bea80-77a1-11eb-8e20-2e968ccd7d9c.png)

As I understand it, the auth module completely ignores these lines
```
        user: {
          property: 'user',
          autoFetch: false
        }
```
Since after each page refresh, the logger in the console shows a request from nuxt
![2021-02-25 19_07_51-Window](https://user-images.githubusercontent.com/46503055/109170156-5cc8c180-77a2-11eb-8318-26fcbe9fa5bc.png)

my auth module config nuxt.config.js
```
  auth: {
    redirect: {
      login: '/login',
      home: '/'
    },
    user: {
      property: 'user',
      autoFetch: false
    },
    strategies: {
      local: {
        scheme: 'refresh',
        token: {
          property: 'accessToken',
          maxAge: 1800,
          type: 'Bearer'
        },
        refreshToken: {
          property: 'refreshToken',
          data: 'refreshToken',
          maxAge: 60 * 60 * 24 * 30,
          type: 'Refresh'
        },
        user: {
          property: 'user',
          autoFetch: false
        },
        endpoints: {
          login: { url: '/api/auth', method: 'post' },
          refresh: { url: '/api/refresh', method: 'post' },
          user: { url: '/api/user', method: 'get' },
          logout: { url: '/api/auth', method: 'delete' }
        }
        
      }
    }
  },
```
current response from server
![2021-02-25 19_54_20-Window](https://user-images.githubusercontent.com/46503055/109171250-6a327b80-77a3-11eb-8668-4834700f346c.png)

**Comment by DmitriyColors** [comment]
@JoaoPedroAS51, while I was writing you have already closed the topic

**Comment by Alwigi** [comment]
> > The problem is the auth.strategies.local.user.autofetch setting, if set to true than all works fine but when set to false then the behaviour is as above.
> 
> Hi @Alwigi! Yes, it's working as expected, this is not a bug. In order to `loggedIn` state be `true`, the user data must be set. When `autoFetch` is set to `false`, you must set the user manually with `setUser({...})` right after login.
> 
> [You can read this for more information](https://auth.nuxtjs.org/schemes/local#backend)

Thanks @JoaoPedroAS51 but I'm not sure I agree. Perhaps I'm misinterpreting but the docs say that you can turn off user fetching if not required, this code works just fine (and there is no user being set):

        user: {
          autoFetch: true
        },
        endpoints: {          
          user: false
        }

but this does not work:

        user: {
          autoFetch: false
        },
        endpoints: {          
          user: false
        }

**Comment by replygirl** [comment]
Hey there! I've been having issues like this and it's been frustrating to see tickets like this repeatedly closed when so many others are having similar issues. Allowing the conversation to continue would keep the issue board clean, as it seems a good 5% of the tickets here are related to reactivity.

I'm using a custom scheme inheriting from `LocalScheme` — the only change is that `fetchUser` interpolates the token into the user endpoint's URL, otherwise functionally identical.

For now, I've found the following watcher on my root layout resolves lifecycle issues with `loggedIn` and `user`, with the side effects of redirects working properly again:

```js
watch: {
  '$store.state.auth.user': {
    handler(x) {
      if (x !== this.$auth.$state.user) {
        this.$auth.$state.loggedIn = !!x?.id
        this.$auth.$state.user = x
      }
    },
    immediate: true,
  },
},
```

**Comment by hicreate** [comment]
@replygirl your solution worked for me in updating the user status without the refresh - thank you.

I still have an issue with not being redirected on login which I can focus on resolving now.

**Comment by replygirl** [comment]
@hicreate At the risk of going off-topic, these are the crucial components for redirecting when the user logs in of their own volition (as opposed to from an auth guard):

```js
export default {
  middleware: ['auth'],
  auth: 'guest',
  mounted() {
    const to =
      this.$historyState.getItem?.(Math.max(this.$historyState._page - 1, 0))
        ?.location?.path ?? '/'

    this.$auth.options.redirect.home = to.startsWith('/login') ? '/' : to
  },
  methods: {
    async onLoginSubmitted() {
      await this.$auth.loginWith('motive', { data: this.login })
    },
  },
}
```

- `middleware: ['auth']` and `auth: 'guest'` ensure that if the user is on this page, they will be redirected to `$auth.options.redirect.home` which we set in `nuxt.config.js`
- The `mounted` hook ensures that whenever the user enters this page, the `$auth.options.redirect.home` is reassigned to wherever they came from, if a previous history state is available. This is possible thanks to @hidekatsu-izuno's [nuxt-history-state](https://www.npmjs.com/package/nuxt-history-state)
