### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by productdevbook** [nuxt-community/auth-module#1109]
### Version
module: 5.0.0-1616003482.75c20e6
nuxt: 2.15.4

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [x] spa

### Nuxt configuration

yarn add --exact @nuxtjs/auth-next and nuxt config add, yarn dev 

![Screen Shot 2021-04-02 at 08 02 48](https://user-images.githubusercontent.com/38668796/113382285-d21f4780-9389-11eb-8246-c17d5731bcc2.png)

* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs

 WARN  in ./node_modules/hasha/index.js                                                      

Module not found: Error: Can't resolve 'worker_threads' in '/a/node_modules/hasha'

This dependency was not found:                                                                               
* fs in ./node_modules/@nuxtjs/auth-next/dist/module.js, ./node_modules/hasha/index.js

**Comment by productfrontenddeveloper** [comment]
axios.ts change algoritma and fixed. Interesting :D

**Comment by jjpark78** [comment]
me too

**Comment by maggi08** [comment]
Did you find Solving?

**Comment by BtheGit** [comment]
Having the same issue.

**Comment by TonalidadeHidrica** [comment]
Same issue here too.  I want at least a workaround.

**Comment by TonalidadeHidrica** [comment]
I tried to add a custom scheme.  As long as the new file is empty, it does not show an error, but once I imported `LocalScheme` from `'@nuxtjs/auth-next'`, it shows an error.  Any idea how to resolve it?  @productfrontenddeveloper

**Comment by TonalidadeHidrica** [comment]
@JoaoPedroAS51 Thank you for your offer!  After struggling for hours I found out the actual cause, which I will describe below.

I was trying to define a custom scheme extending `LocalScheme`.  In `schemes/myCustomScheme.ts` I wrote the following import statement:
```typescript
import { LocalScheme } from '@nuxtjs/auth-next'

export default class MyCustomScheme extends LocalScheme {
  // ...
}
```
This caused the following error message to be output in the `nuxt dev` console:
```
WARN in ./node_modules/hasha/index.js
Module not found: Error: Can't resolve 'worker_threads' in '/a/node_modules/hasha'

This dependency was not found:
- fs in ./node_modules/@nuxtjs/auth-next/dist/module.js, ./node_modules/hasha/index.js
```

The culprit was the import statement.  As written in [official docs](https://auth.nuxtjs.org/guide/scheme#creating-your-own-scheme), and pointed out clearly in [this issue comment](https://github.com/nuxt-community/auth-module/issues/559#issuecomment-765475809) (which definitely saved my day, thanks!), I MUST have import from `~auth/runtime` instead:
```typescript
import { LocalScheme } from '~auth/runtime'
```
Once I replaced the import statement, everything started to work fine.  So in my case, that was the reason.

Again, thank you for helping me out!  @JoaoPedroAS51 
For those who are having trouble with this issue, I hope this information would help!  @maggi08 @BtheGit

**Comment by JoaoPedroAS51** [comment]
Thanks for sharing the solution here. I'm happy to know it's working now! :)

**Comment by yann-yinn** [comment]
If nothings works, try to upgrade your `@nuxtjs/auth-next`. 

`import {LocalScheme} from '~auth/runtime'` is now working for me.

**Comment by productfrontenddeveloper** [comment]
@JoaoPedroAS51 

![CleanShot 2021-08-20 at 06 17 16](https://user-images.githubusercontent.com/38668796/130173778-e8b8ec3b-a220-411c-a77c-4799af62bbd8.png)

interested some some reoad :/

**Comment by productfrontenddeveloper** [comment]
```
import { RefreshScheme, RefreshController, Auth } from '~auth/runtime'


import type {
  TokenableScheme,
  HTTPRequest,
  HTTPResponse,
  SchemePartialOptions,
  CookieSchemeOptions,
  SchemeCheck,
} from '@nuxtjs/auth-next'
``` 
 
 async login(request: HTTPRequest): Promise<HTTPResponse> { 
 
 and fixed, interested :D
