### ISSUE TITLE
do redirects support I18n module? and how to make them do so?

### ISSUE THREAD

**Issue by gimyboya** [nuxt-community/auth-module#1116]
I have asked this question on discord but with no answer so far. I am currently using `nuxt-i18n` and the module provide a specific method for navigation and redirects which is documented [here](https://i18n.nuxtjs.org/basic-usage/#nuxt-link) this allows the user to be redirected to the correct localized page based on the locale they have picked.

my question is does `nuxt-auth` support this feature? if not how can I make it happen? for example can I use a js file for the redirects objec?

**Comment by azrikahar** [comment]
Does this help to achieve what you wanted? https://auth.nuxtjs.org/api/auth#onredirecthandler

To expand on it, since it is auth module's redirect callback and we have access to the `to` portion (which will be `/login` for your scenario), you should be able to do something like this: 

`plugins/auth.js` file

```js
export default function ({ app, $auth }) {
  $auth.onRedirect((to, from) => {
    if (to === "/login") {
      return app.localePath(to);
    }
  });
}
```

and do remember to add the plugin to the auth module in nuxt config:

```js
auth: {
   plugins: [ '~/plugins/auth.js' ]
}
```

**Comment by gimyboya** [comment]
@azrikahar is this `onRedirect` triggered only by the auth redirect and not by any other redirects? if so then it is probably the solution to this problem.

but I don't see why we should only catch the `/login` path as opposed to doing it for all paths by simply returning `return app.localePath(to)`, since our front-end is all translated

Please help me clarify these questions before I proceed into closing this.

**Comment by azrikahar** [comment]
> is this `onRedirect` triggered only by the auth redirect and not by any other redirects?

I believe so, since it's an Auth plugin (nested in auth in nuxt config), unlike typical nuxt plugin. Though I've only tested this in a codesandbox, so I could still be wrong.

> but I don't see why we should only catch the /login path 

that makes sense. My initial code was just an attempt to isolate the code and prevent it firing elsewhere to avoid any unintended behavior. As you mentioned, yes it should work for all routes in theory, but just in case if you ever see any redirect issue, you can put it in an if statement first while reporting the bug if it exist. Hope that helps

**Comment by gimyboya** [comment]
the solution provided by @azrikahar is solving my problem. closing this for now.

thank you @azrikahar
