### ISSUE TITLE
Error when ssr: true

### ISSUE THREAD

**Issue by aversan** [nuxt-community/auth-module#1132]
I'm using @nuxtjs/auth-next in my Nuxt application.
The application is configured using ssr: true

After login, when i reload page i see error
https://gyazo.com/fa98938a1be259a9cc3cc4beba37a9c2?token=fd0c21ec4063f055e4b725933769c0eb

When ssr: false all is ok

this is actual for auth@4.9.1 and auth-next

**Comment by JoaoPedroAS51** [comment]
Hi @aversan! Please, can you rewrite your issue using the [bug report template](https://github.com/nuxt-community/auth-module/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md), otherwise I won't be able to look at it as I need some info about your config. In addition, can you provide more info about your issue, such as what is causing it? This would help me to understand what is happening :)

**Comment by thomas4Bitcraft** [comment]
@aversan Do you found a solution for the problem? I'm currently facing the same issue

**Comment by bmulholland** [comment]
Not enough info, closing
