### ISSUE TITLE
nuxt-vite dev error: cookie/index.js does not provide an export named 'default'

### ISSUE THREAD

**Issue by hojas** [nuxt-community/auth-module#1147]
### Version
module: @nuxtjs/auth-next
nuxt: 2.15.4

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce

build with nuxt-vite

### What is expected?

work fine

### What is actually happening?

Uncaught SyntaxError: The requested module '/@fs/Users/home/my-app/node_modules/cookie/index.js?v=d71b5d6d' does not provide an export named 'default'

**Comment by CodeDredd** [comment]
See https://github.com/nuxt/vite/issues/56#issuecomment-842103085

**Comment by IlyaSemenov** [comment]
`optimizeDeps` is a workaround for broken packages.

The import at https://github.com/nuxt-community/auth-module/blob/532b3d67eec098e9247902cf7b1086f6bd8f4e58/src/core/storage.ts#L3 is (arguably<sup>*</sup>) invalid.

Package `cookie` doesn't have a default export, [it has a few named exports](https://github.com/jshttp/cookie/blob/663c9aeb85c9e046ff2ad2cdec631afdd40a7965/index.js#L15-L16). So it should be:

```ts
 import * as cookie from 'cookie' 
```

---

<sup>*</sup> Granted, it's not that straightforward given that `cookie` uses `exports` instead of `module.exports`, so one may argue that kind of CJS modules always has a default object export. Anyhow, _logically_ it doesn't have a default export, and should be treated as such.
