### ISSUE TITLE
Nuxt auth page reload problem

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [nuxt-community/auth-module#1283]
### Version
module: ^5.0.0-1624817847.21691f1
nuxt: "^2.15.7"

When I log in with nuxt auth, I redirect the user to his profile page. But after reload on the profile page I get an error like this:

### Can not read property 'name' of null 

I have searched this problem related to @nuxtjs/auth-next ssr problem. Most of the solution is to downgrade the @nuxtjs/axios version. I have already tried this but not fixed.

Here is my profile page code:

```
<template>
    <div v-show="$auth.user">
        <!-- profile image -->
        <div class="w-full flex">
            <div>
                <div class="bg-gray-200 p-5 w-40 h-44"></div>
            </div>
            <div class="ml-6">
                <h2 class="font-bold text-2xl mb-4">Profile Details</h2>
                <h6 class="font-semibold text-lg">{{$auth.user.name}}</h6>
                <p><span class="font-medium">Email: </span>{{$auth.user.email}}</p>
                <p><span class="font-medium">Phone: </span>{{$auth.user.phone}}</p>
                <p><span class="font-medium">Last Login: </span>{{$auth.user.lastLoginForHuman}}</p>
                <nuxt-link to="/customer/change-password" class="block mt-3 text-primary-500 text-sm hover:underline">Change Password</nuxt-link>
            </div>

        </div>

        <!-- details -->
        <div class="w-full mt-5">
            <div class="grid grid-cols-2 sm:grid-cols-2 gap-4">
                <input-field label="First name"></input-field>
                <input-field label="Last name"></input-field>
                <input-field type="email" label="Email"></input-field>
                <input-field label="Phone"></input-field>
            </div>

            <div class="flex justify-end">
                <button-field label="Update" class="bg-primary-500 text-white py-3 px-10"></button-field>
            </div>
        </div>

    </div>
</template>

<script>
export default {
    name: "Profile",

    data() {
        return {
            form: {
                firstName: this.$auth.user?.firstName,
                lastName: this.$auth.user?.lastName,
                email: this.$auth.user?.email,
                phone: this.$auth.user?.phone,
            },
            photo: null,
        };
    },
};
</script>
```

**Comment by CodyBontecou** [comment]
This line `<h6 class="font-semibold text-lg">{{$auth.user.name}}</h6>` is probably what's causing the issue. Are you sure your user has a name value?

Check your dev tools vuex User value to see if your user state has a name value. If not, make sure your backend is providing the data you expect.

<img width="294" alt="Screen Shot 2021-08-31 at 13 10 58" src="https://user-images.githubusercontent.com/20440899/131554601-9685e6ab-843e-49ce-873b-cee68b45605c.png">

**Comment by MdMostaFizurRahaman** [comment]
Yes the user has the name property. When it redirects from login to profile
it show all. But after refresh it throws error.

**Comment by devzom** [comment]
Shouldn't be a problem with axios or nuxt-auth. 


for the first maybe use v-if here
```
<template>
    <div v-show="$auth.user">
```


and check if after refresh the page there is going a request to the endpoint which fetch **user** data mostly -> **auth/me** set by default in nuxt-auth. Check the vue-dev-tools if  $auth.user exist

**Comment by alimuradov** [comment]
If you set the   **ssr: false** in file nuxt.config.js then the problem will be solved.
But this solution is probably not suitable for everyone.

**Comment by mjedari** [comment]
Yeah, I have the exact problem. Auth middleware does not recognize user is **logged in** when on **ssr mode**.

**Comment by mjedari** [comment]
> Same problem here

I've fixed it by passinf referer header in nuxt-auth requests.

**Comment by irsyaadbp** [comment]
i have same problem, but now i fixed it
if you setting the proxy with axios there is the problem, because the proxy not work in SSR mode
so i setting base url too
![image](https://user-images.githubusercontent.com/23293993/147423746-fc4543a0-8753-4885-9235-e35f0d77a39a.png)

then in the endpoint setting in nuxt/auth, i remove the /api (proxy) only on user endpoint
![image](https://user-images.githubusercontent.com/23293993/147423788-b8d62a94-3f03-4b28-a6c1-50b9a0c3db0c.png)

and dont forget to setting autofetch to false, because this run in client side, and because we remove the proxy(/api) from user endpoint it will cause error 404 not found
![image](https://user-images.githubusercontent.com/23293993/147423840-9c0eb87b-5807-4286-bcef-fdeb5db76e18.png)

so when the login page we manually fetch the user
![image](https://user-images.githubusercontent.com/23293993/147423867-cf3c4dd4-7781-4ef4-8d4e-74fc3d7c93aa.png)

you can see my full config for nuxt/auth here https://pastebin.com/9d5PbfBN
and yeah its work!

**Comment by bmulholland** [comment]
I think all the tips here are already captured in https://github.com/nuxt-community/auth-module/issues/1197
