### ISSUE TITLE
OAuth 2 flow with external server

### ISSUE THREAD

**Issue by dappiu** [nuxt-community/auth-module#141]
Let me say right away that this is a question and not an issue.

I'd like to be able to execute the OAuth 2 flow with an external server, that exchanges the provider returned `code` with a JWT.  Right now I'm doing the same thing with vue-authenticate by setting the baseUrl config option to the URL of my external API server.
Now, by watching the auth-module code, I kinda figured out that I had to set the `response_type` config option for the strategy to `code`, but in this case the POST request that takes out the code is made to `url: window.location.origin + this.options.access_token_endpoint,` (from /lib/schemes/oauth2.js).
So, it seems to me that I can't forward the POST request to an external server because window.location.origin is always prepended to the URL. Am I right or am I just making some mistake interpreting the code? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c105">#c105</a>)</em></sub></div>

**Comment by robsontenorio** [comment]
@dappiu  Yes it is fixed. Just update to 4.2.0

**Comment by abegehr** [comment]
Great info – This should be added to the docs!

I got it to work, so that the request is forwarded to the server, but on the server side the request has no body data. I'm using bodyParser.json() with my express server.

**Comment by abegehr** [comment]
I figured it out. On the server-side you need to use the bodyParser.urlencoded() parser to get the code at req.body.code.
I think we should:
1) use json data encoding, since this is a JS library
2) add this to the docs at [https://auth.nuxtjs.org/schemes/oauth2.html](https://auth.nuxtjs.org/schemes/oauth2.html)

**Comment by JohannesLichtenberger** [comment]
@abegehr How does Nuxt.js make this call? For instance I have a button with which you get redirected to a Keycloak Login-Page. Fill in the stuff, you get redirected back to a /callback endpoint.

From there on, do we have to extract the code "by hand" and send the code to the token endpoint? I guess not, but I'm struggling with the auth since a few weeks (and I'm super new to frontend stuff in general).

**Comment by sangemi** [comment]
Two major site in my country, naver.com and kakao.com, do not support response_type = 'token'
They only support response_type = 'code'
please give us detail information about response_type = 'code.

[The official doc](https://auth.nuxtjs.org/schemes/oauth2.html#response-type) said that
By default is token. If you use code you may have to **implement a server side logic** to sign the response code.
Is there anyone who can explain the server side logic?

**Comment by sergey-koba-mobidev** [comment]
You may find this example useful - it helped me a lot https://github.com/sirixdb/sirix-web-frontend
