### ISSUE TITLE
Auth0 `audience` parameter is missing

### ISSUE THREAD

**Issue by vladimir-chernenko** [nuxt-community/auth-module#176]
### Reproduction link

[https://auth0.com/docs/api-auth/tutorials/client-credentials#ask-for-a-token](https://auth0.com/docs/api-auth/tutorials/client-credentials#ask-for-a-token)

### Steps to reproduce

Hi, I'm using this module for authorization to my django rest api. At the beginning I was getting back strange short  `Bearer` token without API access.
Then I understood that the `audience` parameter is  missing on login redirect.

https://github.com/nuxt-community/auth-module/blob/dev/lib/schemes/oauth2.js#L47

### What is expected ?

May be options should be updatable?
Or how I can extend auth module to custom login function?

### What is actually happening?

Unauthorised access to API

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c134">#c134</a>)</em></sub></div>

**Comment by chrpeters** [comment]
Tried this as well and the problem is, that the module cleans up the files and copies only the schemes that are needed. So when using the new auth0Scheme, the oauth2Scheme ist not copied anymore. After adding a strategy that uses oauth2 to the list of strategies ( like github: { })  in nuxt.config.js, it worked.

after that i got an error, that the parseQuery method could not be found, so i included the imports from the oauth2scheme into the auth0scheme as well:
`import { encodeQuery, parseQuery, randomString } from '../utilities'`
