### ISSUE TITLE
How to set object user property

### ISSUE THREAD

**Issue by duongxinh2003** [nuxt-community/auth-module#1835]
Hello guys!

I want to set user property response base on object like this:
```{
    "id": 1,
    "login": "admin",
    "firstName": "Administrator",
    "lastName": "Administrator",
    "email": "admin@localhost",
    "imageUrl": "",
    "activated": true,
    "langKey": "en",
    "authorities": [
        "ROLE_USER",
        "ROLE_ADMIN"
    ]
}
```
But I read document only set user property by one string field:

```
user: {
          property: 'firstName',
          autoFetch: true,
        }
```
How can I fetch all response object user information?Thanks!

**Comment by skoenfaelt** [comment]
In your component you do something like that

```
 const { data } = await this.$auth.loginWith('local', {
          data: { email, password },
        })
```

In that Data object you should get your object as stated in your question. Now you can create a postLogin action in your vuex store or call the upcomming vuex change in your method. 

`commit('auth/SET', { key: 'user', value: YOUR_CUSTOM_USER_OBJECT}, { root: true })`

and I think you should set ` user: false,` in your auth module config, since YOU want to handle the user data and not the authModule.
In that specific case you are more flexible with setting up the user. In our case the avatar is not directly set on the user, we got a separate api endpoint, so after the login I want to set the url as the icon, so the image src get the avatar via url.
