### ISSUE TITLE
signUpWith() -> open default signUp flow in Auth0 

### ISSUE THREAD

**Issue by birdlavv** [nuxt-community/auth-module#233]
### What problem does this feature solve?

Currently ```loginWith('auth0')``` opens up the default login flow. This works well with "Login" buttons, but there is currently no option to trigger the "Sign Up" flow that Auth0 provides.
While there aren't much docs to go on,
https://auth0.com/docs/libraries/lock/v10/configuration#initialscreen-string-
there are a few discussions:
https://community.auth0.com/t/hosted-pages-link-to-signup-or-login-as-intial-screen/7845/3
https://community.auth0.com/t/how-to-open-login-signup-on-the-universal-login-hosted-page/12642/2

### What does the proposed changes look like?

perhaps something like:
     ```GET https://YOUR_AUTH0_DOMAIN/authorize?
     response_type=code|token&
     client_id=YOUR_CLIENT_ID&
     connection=CONNECTION&
     redirect_uri=https://YOUR_APP/callback&
     state=STATE
     &mode=signUp```

The ```&mode=signUp``` would be a custom param & would be passed to ```initialScreen: config.extraParams.mode``` in the lock. This would require a small explanation in the docs, describing how to add the custom param line to the lock template in the Auth0 UI

<!--cmty-->
<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c190">#c190</a>)</em></sub></div>

**Comment by reinoldus** [comment]
Are there any news regarding this issue? Is there an alternative way to achieve this?

**Comment by codeofsumit** [comment]
Is there a workaround for this? I want Sign Up buttons to show the signup form of course

**Comment by pi0** [comment]
**UNTESTED**

I think you can do this:

```js
$auth.loginWith('auth0', { params: { mode: 'signup' } })
```

**Comment by codeofsumit** [comment]
Doesn't work for me 😞

**Comment by pi0** [comment]
Hi again. I did a little more research on the auth0 login experience. As explained in [Login with Auth0](https://auth0.com/docs/login) there are two difference experiences Universal and Classic which you have to switch to new one if want directly going to signup page:

![image](https://user-images.githubusercontent.com/5158436/78235749-6043c200-74d9-11ea-8af7-e7bf893e8dba.png)

After upgrading to [Universal Experience](https://auth0.com/docs/universal-login/new#signup), we have to provide two params in order to always show signup page to users:

```js
$auth.loginWith('auth0', {  params: {  screen_hint: "signup", prompt: 'login' } })
```

![image](https://user-images.githubusercontent.com/5158436/78235978-ae58c580-74d9-11ea-84d8-24be853928b4.png)

**Comment by codeofsumit** [comment]
Awesoooome ❤️ 😍  it works!!! 🎉
