### ISSUE TITLE
laravel passport example

### ISSUE THREAD

**Issue by darkwoods-** [nuxt-community/auth-module#24]
Is there anyone who is willing to share/show a full example of this with Laravel Passport?
I mean like a repository or even a small tutorial about it all?

Sorry for my n00bity here but I think this would help many people like me.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c18">#c18</a>)</em></sub></div>

**Comment by kennonb** [comment]
I struggled with this too and I spend way too much time working this out. I'll detail my steps that I took and maybe I can put together a small repo with a simple example of this for others.

1. npm install `@nuxtjs/auth-module` & `@nuxtjs/axios-module`

```js
npm install @nuxtjs/auth @nuxtjs/axios
```

2. Add both modules to `nuxt.config.js`

```js
modules: ["@nuxtjs/axios", "@nuxtjs/auth"],
```

3. Add `auth` middleware to`nuxt.config.js`

```js
router: {
    middleware: ["auth"]
},
```

4. Add `auth` options to `nuxt.config.js` to define the URLs that this package should hit to authenticate users. 

_Note:_ Change the `propertyName` attributes to match what your API will return when authenticating. Mine returns an `access_token` attribute in the JSON, so I put that there, and when I grab the logged in user it just returns a default `data` object, so that's what I put in the `user` object.

```js
  auth: {
    endpoints: {
      login: {
        url: `FULL_URL_TO_LOGIN_ROUTE_TO_OBTAIN_ACCESS_TOKEN`,
        method: "post",
        propertyName: "access_token"
      },
      logout: {
        url: `FULL_URL_TO_LOGOUT_ROUTE`,
        method: "post"
      },
      user: {
        url: `FULL_URL_TO_ROUTE_TO_RETRIEVE_LOGGED_IN_USER_DETAILS`,
        method: "get",
        propertyName: "data"
      }
    }
  }
```

5. Create a `login.vue` page to handle a user entering their credentials with a method for send the login request.

_Note:_ I changed the params that the `$auth.login` is passing through to my API to match what my API expects to receive.

```html
<template>
  <div>
    <h1>Login</h1>
    <p>Please enter your credentials below to login.</p>
    <form>
        <input :name="email" label="Email Address" type="text">
        <input :name="password" label="Password" id="password" type="password">
        <button @click="login">Login</button>
      </form>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        email: '',
        password: ''
      };
    },

    methods: {
      login: function () {
        this.$auth.login({
          data: {
            email: this.email,
            password: this.password
          }
        });
      }
    }
  }
</script>
```

6. Open `http://localhost:3000`
7. You should see your login route to begin the login process.

Once a login request is completed, the application should automatically recognize the authenticated user and will allow you past the "guard" that was put in place in Step 3. It should redirect you to the page you originally tried to access.

Things that I still need to finish up in this example:

- [ ] Error pages
- [ ] Logout route
- [ ] A refresh token interceptor?

**Comment by jmschneider** [comment]
Here is a [repo](https://github.com/jmschneider/nuxt-laravel-passport-example) of a basic setup. There is a lot I'd like to improve but it might give you a basic idea of where to start.

**Comment by pi0** [comment]
Nice stuff @jmschneider! You can make a PR to officially point to your starter example in the recipes section 😊

**Comment by jmschneider** [comment]
@pi0 I tried to take a little further and created a [provider for Laravel Passport](https://github.com/nuxt-community/auth-module/pull/157). I think the initial solution in that repo would actually end up exposing the client secrets on the client side.

**Comment by galpratama** [comment]
When will this released? Or it is safe to use dev branch?

**Comment by mwargan** [comment]
Hey @jmschneider! Thanks for your repo, but it left me a bit confused :P! Don't the password_grant and password_grant_custom schemes publicly expose the client_secret, therefore creating a massive security risk? I've also tried the "laravel.passport" provider on my static pwa hosted on S3, but the problem is that upon my API returning the code, the Auth module attempts to make a post request to _auth/oauth/laravel.passport/authorize, but S3 can't support POST requests and there is no directory like _auth in the dist after running nuxt build.

How can I authenticate a static PWA with an API using Laravel Passport?

**Comment by jmschneider** [comment]
Hey @mwargan,

You are correct, in the final implementation of  the `laravel.passport` provider it sends the request to the Nuxt server to [attach the client secret and proxy it](https://github.com/nuxt-community/auth-module/blob/dev/lib/providers/_utils.js#L8-L70) on to Laravel Passport. I think you might be able to do something with an [implicit grant token](https://laravel.com/docs/5.6/passport#implicit-grant-tokens) in order to authenticate without a client secret. I don't remember exactly how you would set up the Nuxt auth side of things.

There are also some additional options you can override in the settings you can see [here](https://github.com/nuxt-community/auth-module/blob/dev/lib/providers/laravel.passport.js). I believe the `authorization_endpoint` option is setting where the initial request goes. Changing that to point directly to the Laravel Passport endpoint might work.

**Comment by mwargan** [comment]
Ahh - I was thinking this was a case for an Implicant Grant Token. Are you saying I could do this using the `laravel.passport` provider? Could you throw together a very simple/quick example?

So no way to use a Password Grant in this case?...

**Comment by stuntrocketdanny** [comment]
There are some ideas here on how to use a local/proxied API call (in order to not expose client secret).

https://esbenp.github.io/2017/03/19/modern-rest-api-laravel-part-4/

**Comment by spacemudd** [comment]
nuxt.config.js

```
{
auth: {
    login: '/login',
    logout: '/',
    strategies: {
      local: {
        endpoints: {
          login: {url: '/api/auth/login', method: 'post', propertyName: 'access_token'},
          logout: {url: '/api/auth/logout', method: 'post', },
          user: {url: '/api/auth/user', method: 'get', propertyName: 'user'},
        },
        tokenRequired: true,
        tokenType: 'Bearer',
      },
    }
}
```

`tokenType` is case-sensitive and should be `Bearer`. [Check this Illuminate trait where it looks for `Bearer`.](https://github.com/laravel/framework/blob/b4fe271c9001b79dacdb76075e32ad795579ceb7/src/Illuminate/Http/Concerns/InteractsWithInput.php#L57)

And in your controllers/services, you can have similar code:

```
Route::post('auth/login', function(Request $request) {
    $cred = $request->only('email', 'password');

    if (auth()->attempt($cred)) {

        auth()->user()->tokens()->delete();
        $token = auth()->user()->createToken('SPA');

        return response()->json([
            'access_token' => $token->accessToken,
        ]);
    }

    return response()->json(['Unauthorized.'], \Illuminate\Http\Response::HTTP_UNAUTHORIZED);
});

Route::group(['middleware' => 'auth:api'], function() {
    Route::get('auth/user', function(Request $request) {
        return auth()->user();
    });
});
```

**Comment by connecteev** [comment]
Really need this too, if anyone can point out an end-to-end example using Laravel passport that would be helpful

**Comment by spacemudd** [comment]
@connecteev Check my previous post. This is how you would do it with Passport. I wrote a small Medium article: https://medium.com/@shafiqalshaar/laravel-passport-nuxt-auth-the-simple-way-da302add5151 however, it's not really utilizing a JWT token with payload and/or expiry.

**Comment by connecteev** [comment]
@spacemudd thanks..do you know how to do auth for social login + laravel passport? It would use the [authorization code grant](https://oauth2.thephpleague.com/authorization-server/which-grant/) I believe.

**Comment by nmsmith22389** [comment]
Why is this so tough?
Most examples are mountains of code and still end up exposing the `client-secret`.

I would think that Laravel Passport + Nuxt would be a super common way of doing things.

Has anyone made any more progress?

**Comment by devondahon** [comment]
I'm also trying to use **Laravel 7.3 Passport** with **Nuxt.js**, but still unsuccessfully.

My first step was to edit the file `config/cors.php` in **Laravel** and change the paths trait this way:
```
// 'paths' => ['api/*'],
'paths' => ['*'],
```

Then, in my **Nuxt.js** config, I have the following authentication  configuration in `nuxt.config.js`:
```
  auth: {
    strategies: {
      'laravel.passport': {
        url: process.env.LARAVEL_ENDPOINT,
        client_id: process.env.PASSPORT_PASSWORD_GRANT_ID,
        client_secret: process.env.PASSPORT_PASSWORD_GRANT_SECRET
      }
    }
  },
```

But when I use it with `this.$auth.loginWith('laravel.passport')`, I'm redirected to my `http://laravel.test/login` page, then I log in and get the following error message:

> {"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}

What's wrong in this configuration ?

**Comment by devondahon** [comment]
Actually, if I add the `redirect_uri`, I can login with **Laravel** and be redirected to **Nuxt** with a `code` and `state`, but then what should I do with these parameters to get a token and have the **auth module** configured ?
```
  auth: {
    strategies: {
      'laravel.passport': {
        url: 'http://laravel.test',
        client_id: 2,
        client_secret: S0gpvIHCL3j5IDgbmcgfiTsTUMOR0kdaCi
        redirect_uri: 'http://localhost:3000'`
      }
    }
  },
```

**Comment by JoaoPedroAS51** [comment]
Closing here, as docs already have [laravel passport provider](https://auth.nuxtjs.org/providers/laravel-passport).

Demo code: [nuxt.config.js](https://github.com/nuxt-community/auth-module/blob/dev/demo/nuxt.config.ts#L87) and [laravel-auth repo](https://github.com/pi0/laravel-auth)
