### ISSUE TITLE
Documentation on how the redirect query is used

### ISSUE THREAD

**Issue by mauxtin** [nuxt-community/auth-module#302]
### What problem does this feature solve?

I want to redirect back to the previous page after login but I cannot find anything in the docs.

When I go to the login page with the previous path as a query param e.g. `/login?redirect=/page1/page2`, I want to be redirect back to it after successful login.

I found this PR (https://github.com/nuxt-community/auth-module/commit/dde409af9b4b9b4cb899488889015e04a00c5255#diff-45ced1ab657dd3dcf5d098a56bc0f039R287) here but I am unsure how to use it.

This seems like a basic thing that the docs should have already included.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c279">#c279</a>)</em></sub></div>

**Comment by joergac** [comment]
I am actually looking for this exact thing too. Did you find a way to solve this @mauxtin?

**Comment by dappiu** [comment]
I think the PR you referenced is old. Now, instead of relying on URL query parameters, the `redirect` state is set like this [using $auth.$storage](https://github.com/nuxt-community/auth-module/blob/8c1567a9fd77bcebb5af41a1be31740dfded95a8/lib/core/auth.js#L341)

So, if you're using the 'auth' middleware on protected routes and the user is not loggedIn, the middleware saves the intention of being redirect to that route after a successful login. before redirecting to the login page. Then, when redirect('home') is called (at the end of a successfull `loginWith('local', { ... })`, for example), if rewrteRedirects is not false, the auth module instead of redirecting you to the home (and I mean `redirect.home` option in module config), it will redirect you to the protected endpoint that you tried to visit just before being redirected to the login page (and I mean `auth.redirect.login in module options`).

BUT, as you said the feature is not documented well and, plus the examples are outdated since they are using `$auth.$store.redirect` to check if a value is present, but my Vuex store inside the `auth` submodule shows only `user`, `strategy`, and `loggedIn`.  The only way I found to get the `redirect` value, if any, is to call `$auth.$storage.getUniversal('redirect')`
I'm also experiencing some discrepancies from server-side state and browser state (if I, logged out, access a protected route directly, I'm not seeing the 'redirect' value set on browser side, only if I'm clicking on a nuxt-link from another route), but currently I'm unable to tell what the problem is and I'm looking at the code right now, I hope to get back soon with more details.

**Comment by mauxtin** [comment]
Hey @dappiu, for now I disabled the redirect completely and I am handling it on my own. 

This library seems like it is in maintenance mode only for now so I don't really expect this to change anytime soon (considering there are a bunch of open issues & PRs that are not addressed).
