### ISSUE TITLE
This module redirect me back to login even if i am logged in on restarting the browser

### ISSUE THREAD

**Issue by Awais-cb** [nuxt-community/auth-module#314]
I am facing strange issue this package has its local strategy does not respond the way it should,this plugin keeps redirecting me to login route even if i was logged i just closed the browser and reopened it again and hit the home url but i was redirected to login route for unknown reason.Also on login the redirect stays on login no matter what url i add up for home here is my local strategy
```  auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: 'users/signin', method: 'post', propertyName: 'user.token' },
          user: { url: 'users/me', method: 'get', propertyName: 'data' },
          logout: false
        },
        tokenRequired: true,
        tokenType: 'Bearer'
      }
    },
    redirect: {
      login: '/login',
      logout: '/login',
      callback:'/',
      home: '/profiles',
    },
    rewriteRedirects: true,
    watchLoggedIn: true
  },```
Any help regarding this issue will be really appreciated.

**Comment by roelmagdaleno** [comment]
I'm having the same issue but when I refresh the current page after my user log in, have you solved it? :/

**Comment by duongtdvn** [comment]
I'm facing the same issue, disable the user end point by setting it to `false` solve the problem but i need that endpoint sadly :(

**Comment by martinrisseeuw** [comment]
I have the same issue. Anyone found a solution?

**Comment by kamilcglr** [comment]
Are we doing something wrong? Doesn't anyone else have this problem?

**Comment by jasonlyu123** [comment]
This happened in universal mode. This is what I found out, correct me if I am wrong. When the browser restart, the session cookie got discarded so the ssr won't have the token to authenticate. Because firefox would restore the cookie this won't happen to firefox.

About the redirect after login, when you load the page the auth module would extract the token from local storage. Becuase of the token is still there, auth module would set `loggedIn` state in the vuex store to true. So it might not trigger redirect after logged in. The default login method would call a reset method so it would always redirect. If you disabled the login endpoint like this.
```js
  auth: {
    strategies: {
      local: {
        endpoints: {
          login: false,
        },
      },
    },
}
```
And use `this.$auth.login()` to redirect after your custom login login. Be sure to call `this.$auth.reset()` first
