### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by freearhey** [nuxt-community/auth-module#515]
As I see, most bugs and questions have not been solved for a couple of years. So this project is dead, right?

Maybe somebody can recommend a worthwhile replacement, then.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c471">#c471</a>)</em></sub></div>

**Comment by Atinux** [comment]
Well it is not dead, but we had some work to do on the core repo. Any help is more than wanted, you can join our Discord if you want us to guide you to help :)

https://discord.nuxtjs.org

**Comment by freearhey** [comment]
@Atinux So it's okay for you not to fix bugs for a few years?

And I would help if I saw that the core of the team takes care of its projects, but in this case it is definitely not.

**Comment by dappiu** [comment]
@freearhey which bugs are we talking about? Almost all open issues on this repository are not due to bugs but to misconfigurations introduced by users which don't fully understand how this module and Nuxt work. I'm using this module without problems with the "local" scheme and the OAuth scheme from different providers.
We can talk about lacking features, as with token refresh support, but I don't think there are currently bugs with the intended usage of the module.

**Comment by freearhey** [comment]
So all the issues are incorrectly labeled as bugs and it's just problems that users of this module have faced and are simply ignored all these years? Do I understand you correctly?

**Comment by dappiu** [comment]
The issues labeled `cmty:bug-report` are just issues that were opened using cmty.app, and to get the label you just have to fill all the required fields.
I'm not saying that ALL the issues are just users problems, but the majority are. Take for instance the many issues regarding wrong redirects or "user that doesn't stay logged in after page refresh", all of these regards bad configuration and I wasn't able to reproduce any of this.
The large number of opened issues is indeed due to the fact that this module is not very user friendly, but authentication and security in first place are not user friendly, so it's easy for users to fall short on those. 
The large number of issues due to misconfigurations made very hard for anyone to check and reply to every opened issue, and here we are today.

Since version 4.8.4 I can confirm the module is working perfectly on SPA/Universal/Generated sites for the intended usage with JWT tokens or with provided OAuth providers.

**Comment by freearhey** [comment]
So what prevents the team from answering these people's questions? As you correctly noticed it is not a very user friendly project, so ignoring user questions seems even more incorrect to me.

This is what I see:
- 74 open issues
- 22 pull requests
- poor documentation
- zero support

And even if I find a new bug it will be easier for me to find a new module than to convince the team to fix it.
