### ISSUE TITLE
Auth0 Twitter Sign-On does not work

### ISSUE THREAD

**Issue by pekalicious** [nuxt-community/auth-module#526]
### Version

[v4.8.5](https://github.com/auth-module/releases/tag/v4.8.5)

### Reproduction link

[https://github.com/nuxt-community/auth-module/tree/dev/examples/demo](https://github.com/nuxt-community/auth-module/tree/dev/examples/demo)

### Steps to reproduce

- Clone repo
- Set your auth0 domain, client_id, and audience setting in `nuxt.config.js` 
- Follow Auth0's [tutorial to setup Twitter login](https://auth0.com/docs/connections/social/twitter)
- Enable Twitter connection in your Auth0 tenant
- Make sure you have Universal Login and it's set to Classic
- Run demo
- Hit "Login with Auth0"
- Hit Twitter button

### What is expected ?

Be able to signup/login with Twitter

### What is actually happening?

Twitter calls callback with an error:

http://localhost:3000/callback#error=access_denied&error_description=InternalOAuthError%3A%20Could%20not%20authenticate%20you.&state=XXXXXXXXX

### Additional comments?

GitHub login works fine. Username/Password works fine.

Twitter does not work. Google does not work either.

When trying to login to Twitter I get this error:

Error: access_denied
Error Description: InternalOAuthError: Could not authenticate you

For Google I get:

Error: invalid_request
Error Description: Unauthorized

I'm opening this issue as instructed by Auth0: https://community.auth0.com/t/can-login-with-github-but-not-twitter-or-google/36699

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c485">#c485</a>)</em></sub></div>

**Comment by bmulholland** [comment]
Following these repo steps would take me hours, and the original site is on hold, so closing. If this is still a problem, please open a new issue with a simplified, runnable repro I can try myself.

**Comment by KenEucker** [comment]
@bmulholland I am getting this error with Twitter API v2 and I believe that this is an Auth0 issue. Can anyone here provide insight on what resolved their issues?

**Comment by pekalicious** [comment]
@KenEucker FWIW I never resolved the issue. I just didn't enable Twitter :/

**Comment by KenEucker** [comment]
@pekalicious I got it working! It turns out that I needed to enable the authentication settings in the Twitter API by what I thought appeared to be a wizard-style call to action, that lead me to the /auth-settings page.

![Screen Shot 2022-02-22 at 6 25 58 PM](https://user-images.githubusercontent.com/1720267/155252324-42d46fa2-24ee-49ee-837b-701e995c2624.png)

My authentication settings for Twitter API V2 with Auth0:

![Screen Shot 2022-02-22 at 6 26 13 PM](https://user-images.githubusercontent.com/1720267/155252348-d396ec85-0492-4bdd-ba16-fd938b56bc36.png)

And then in Auth0 social connections:

![Screen Shot 2022-02-22 at 6 29 31 PM](https://user-images.githubusercontent.com/1720267/155252511-2f06f272-2155-40f4-a569-d50b653b400a.png)

**Comment by pekalicious** [comment]
Nice! Thanks for sharing your settings. I'll see if I can get it to work too!
