### ISSUE TITLE
where can i see an example local auth (using cookie) on serverMiddleware

### ISSUE THREAD

**Issue by b01110011** [nuxt-community/auth-module#574]
I can't find an example server-side authorization code.

```
// url: '/api/auth/login'
export default async function(req, res, next)
{
    // req.body.email req.body.password
    // query to db
    // what do I need to return and do to implement authorization
}
```

**Comment by hktr92** [comment]
I have managed to "reverse-engineer" this part of functionality. All you have to do in your login endpoint is to:
- check if user exists
- check if password is valid and matches
- if you're using authentication token / api token: generate a new token / register device / whatevs (advanced case)

the return part depends on what you want to use in your frontend: 
- you can either use [a single key from user (e.g. username or e-mail)](https://auth.nuxtjs.org/schemes/local.html#propertyname)
- you can either set `propertyName` to `false` and use the whole `user` object (if you want to check for roles, display full name and username, set user defined language from db, etc.)

but for most cases, the `{ username, displayName }` should suffice in most frontend projects.

here is an additional api file to guide you: [nuxt-community/auth-module/blob/dev/demo/api/auth.js](https://github.com/nuxt-community/auth-module/blob/dev/demo/api/auth.js)

**Comment by slidenerd** [comment]
I double this, I could not find an example of setting cookies and have the following doubts
- I see the documentation of nuxt-auth [HERE](https://auth.nuxtjs.org/schemes/local.html#options) what about  autoFetchUser? should I add that to cookie based flow or not
- What about the endpoint itself, what is the return object format of /api/auth/login on success and on error?
- Will using cookie-session or express-session work here instead of JWT?
- does the cookie get extended automatically each time person visits the page or is this done server side with express-session?
- how do you do Facebook/Google login with cookies or say in general how do you implement an OAuth scheme with cookies? I am guessing the callback URL needs to point to an endpoint on your server such as /auth/facebook/callback What is the format of the object returned here on success/failure
- Can somone kindly answer these questions

**Comment by b01110011** [comment]
i using Adonis Js as backend, there is module auth released in the box.
https://adonisjs.com/docs/4.1/installation
Recommend!

**Comment by UnlimitedBytes** [comment]
I made an example using nuxtjs, nuxt-auth, mongoose, express-sessions you can find it here: https://github.com/UnlimitedBytes/nuxt-auth-example

**Comment by slidenerd** [comment]
@UnlimitedBytes could you update all your dependencies in package.json to the latest version and then run the webapp, does it still work?

**Comment by UnlimitedBytes** [comment]
@slidenerd Yes it still works. I also updated the dependencies in the repo to the latest versions.

**Comment by mypirateapp** [comment]
@UnlimitedBytes nice repo! if you dont mind can you also add passport-facebook to it, how would your code work with this.$auth.loginWith('facebook')

**Comment by armanivvv** [comment]
Did anyone get the repo or fork it before UnlimtedBytes decided to vanish from Github?

**Comment by bmulholland** [comment]
Looks like there's a fork here: https://github.com/slidenerd/nuxt-auth-example

Also note that [the demo folder of this repo](https://github.com/nuxt-community/auth-module/tree/dev/demo) has an example implementation.
