### ISSUE TITLE
why fetch user only works in client side

### ISSUE THREAD

**Issue by GMounir** [nuxt-community/auth-module#834]
I connect nuxtjs with laravel 8 using sanctum cookies
with postman everythings works good,
i login the user in client side with nuxtjs and using auth module
```
  await this.$axios.$get('/sanctum/csrf-cookie')

  let response = await this.$auth.loginWith('local', { data: this.form })
```
at this moment the user is logged in...

but when i refresh the page 'api/user' return the user but only in client side! in the server side get html text like in the screenshot
<img width="1213" alt="Screen Shot 2020-09-19 at 1 02 07 PM" src="https://user-images.githubusercontent.com/13512081/93667016-96bacc80-fa7a-11ea-8ecf-35622ab1aa9a.png">
please any help, this it is takes me a lot of time and effort

**Comment by msonowal** [comment]
@GMounir 
Please check your serverside code it is not responding same response maybe based on the accept header.
Show your server side code

**Comment by JoaoPedroAS51** [comment]
Hi @GMounir! You should use [laravel sanctum provider](https://auth.nuxtjs.org/providers/laravel-sanctum) that is available in auth v5. I believe it will fix your issue or at least give you an error in json, which would make it much easier to understand what is happening.

But I'll be closing here, as this is an old issue and due to inactivity. Feel free to reopen if issue persist :)
