### ISSUE TITLE
Scope not working with github

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [nuxt-community/auth-module#932]
Hello!!

I am trying to use the GitHub app authentication but I am unable to get the user email.  I've tried adding to the scopes `scope: ['user:email']` but the email is returned as null.

Is it possible to get the email without additional configuration? Am I missing something?

Thanks in advance!

**Comment by bmulholland** [comment]
Can you post more information? How do you know that the email is returned as null? How do you know this is a bug with the auth module, rather than, say, GitHub? (I know this is v. unlikely, but investigating that possibility is likely to uncover useful information) Is it possible that you're trying to access the email at the wrong method name?

**Comment by Quaiks** [comment]
I will put together a little project to reproduce the issue!
