### ISSUE TITLE
How to reload all browser tabs when logout

### ISSUE THREAD

**Issue by jonalxh** [nuxt-community/auth-module#995]
Hi, I want to know how to force all tabs to reload or go to home page when logout is invoked in one of the tabs, the current behavior is that current tab goes to $auth.options.redirect.logout endpoint, but the others dont. How to achieve it?

**Comment by jonalxh** [comment]
I've tried and logging in from one tab does not sync with the other tabs either.

**Comment by bmulholland** [comment]
Sorry, managing state across multiple tabs isn't supported.

**Comment by jonalxh** [comment]
By using persisted state or another library like multiTabState could it be solved?

**Comment by trandaison** [comment]
@bmulholland Consider this case. 
- Open the 1st tab, login to the account#1.
- Open the 2nd tab (account#1 is already logged in), do logout, then login with account#2 (another account).
- Back to the first tab, navigate to any page by clicking nuxt-link (not refresh the whole app), `$auth.user` object will be the data of account#1, but the tokens are now from account#2.

**Expected behavior:**
The `user` object should be sync between tabs.

**Comment by bmulholland** [comment]
@trandaison That's a very advanced use case that won't be used by 99%+ of applications or users. If a real-life application needs to support multiple logins, they should instead build that in as a first-class feature. For users with advanced needs, they can use multiple browsers, or the multi-profile support that both Chrome and Firefox use. The complexity vs value tradeoff makes it a non-starter.

**Comment by trandaison** [comment]
@bmulholland No, I don't think it's multiple login. You might get me wrong.
I've just logged in ONE account at a moment. Not log in 2 accounts on 2 tabs at the same time.
The point is, `$auth.user` object from the previous user was cached until the page refreshes.

**Comment by jonalxh** [comment]
I agree with @bmulholland the problem is that you need to reload the browser tab to get or delete the user details, it does not refresh automatically and I think it should, because it uses a kind of Vuex inside.

**Comment by igor-leschikov** [comment]
You can add global EventListener on storage.

```
mounted() {
    window.addEventListener("storage", (event) => {
      if (event.storageArea != localStorage) return;
      if (event.key === "auth._token.local") {
        location.reload();
      }
    });
  },
```

**Comment by CJxD** [comment]
I'm a bit concerned with how this issue has been brushed off with a hacky workaround.

I think it's important to log out the user if they log out in other tabs otherwise information can be leaked. Since navigation is a client-side thing, you can pretty much browse an entire site even though the user has logged out.

In addition to the above, I also added the following check to log the user out when they navigate to a new page after the token has been cleared:

```
mounted() {
    const tokenKey = '_token.local';

    window.addEventListener('storage', (event) => {
      if (event.storageArea !== localStorage) {
        return;
      }
      if (event.key === `auth.${tokenKey}`) {
        location.reload();
      }
    });

    this.$router.beforeEach((to, from, next) => {
      const authToken = this.$auth.$storage.getUniversal(tokenKey);
      if (!authToken) {
          location.reload();
      }
      next();
    });
}
```
